version: '3'
services:
  web-notepad:
    image: lissettecarlr/web-notepad:latest
    ports:
      - "12345:12345"
    environment:
      - UPLOAD_PASSWORD=1234
    volumes:
      - ./notes:/app/notes
    restart: always 